"""fix_uuid_for_sqlite_compatibility

Revision ID: 1f2c7fad5680
Revises: 3b9529b3fccd
Create Date: 2026-06-03 18:10:56.641918

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1f2c7fad5680'
down_revision: Union[str, None] = '3b9529b3fccd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
