"""fix_moderator_model_for_sqlite

Revision ID: 3b9529b3fccd
Revises: c00e1659757f
Create Date: 2026-06-03 17:43:40.395940

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3b9529b3fccd'
down_revision: Union[str, None] = 'c00e1659757f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
