"""initial_migration_with_canon_models

Revision ID: 6dda6ee31abe
Revises: 
Create Date: 2026-06-03 14:00:33.189090

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6dda6ee31abe'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('blocking_reasons',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('code', sa.String(length=64), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('hard_block', sa.Boolean(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_blocking_reasons_hard_block', 'blocking_reasons', ['hard_block'], unique=False)
    op.create_index('idx_blocking_reasons_is_active', 'blocking_reasons', ['is_active'], unique=False)
    op.create_index(op.f('ix_blocking_reasons_code'), 'blocking_reasons', ['code'], unique=True)
    op.create_table('idempotency_keys',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('key', sa.String(length=36), nullable=False),
    sa.Column('processed_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_idempotency_keys_key'), 'idempotency_keys', ['key'], unique=True)
    op.create_index(op.f('ix_idempotency_keys_processed_at'), 'idempotency_keys', ['processed_at'], unique=False)
    op.create_table('moderation_tasks',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('product_id', sa.String(length=36), nullable=False),
    sa.Column('seller_id', sa.String(length=36), nullable=False),
    sa.Column('category_id', sa.String(length=36), nullable=True),
    sa.Column('kind', sa.String(length=20), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('queue_priority', sa.Integer(), nullable=False),
    sa.Column('assigned_moderator_id', sa.String(length=36), nullable=True),
    sa.Column('json_before', sa.JSON(), nullable=True),
    sa.Column('json_after', sa.JSON(), nullable=False),
    sa.Column('claimed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('claim_expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('decision_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('decision_comment', sa.String(length=2000), nullable=True),
    sa.Column('blocking_reason_id', sa.String(length=36), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_tasks_assigned_moderator', 'moderation_tasks', ['assigned_moderator_id'], unique=False)
    op.create_index('idx_tasks_product_id', 'moderation_tasks', ['product_id'], unique=False)
    op.create_index('idx_tasks_queue_priority', 'moderation_tasks', ['queue_priority'], unique=False)
    op.create_index('idx_tasks_status', 'moderation_tasks', ['status'], unique=False)
    op.create_index('idx_tasks_status_queue_created', 'moderation_tasks', ['status', 'queue_priority', 'created_at'], unique=False)
    op.create_index(op.f('ix_moderation_tasks_assigned_moderator_id'), 'moderation_tasks', ['assigned_moderator_id'], unique=False)
    op.create_index(op.f('ix_moderation_tasks_product_id'), 'moderation_tasks', ['product_id'], unique=False)
    op.create_index(op.f('ix_moderation_tasks_queue_priority'), 'moderation_tasks', ['queue_priority'], unique=False)
    op.create_index(op.f('ix_moderation_tasks_status'), 'moderation_tasks', ['status'], unique=False)
    op.create_table('moderation_comments',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('task_id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('is_from_moderator', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['task_id'], ['moderation_tasks.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('product_snapshots',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('task_id', sa.String(length=36), nullable=False),
    sa.Column('snapshot_type', sa.String(length=20), nullable=False),
    sa.Column('data', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['task_id'], ['moderation_tasks.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_snapshot_task_type', 'product_snapshots', ['task_id', 'snapshot_type'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_snapshot_task_type', table_name='product_snapshots')
    op.drop_table('product_snapshots')
    op.drop_table('moderation_comments')
    op.drop_index(op.f('ix_moderation_tasks_status'), table_name='moderation_tasks')
    op.drop_index(op.f('ix_moderation_tasks_queue_priority'), table_name='moderation_tasks')
    op.drop_index(op.f('ix_moderation_tasks_product_id'), table_name='moderation_tasks')
    op.drop_index(op.f('ix_moderation_tasks_assigned_moderator_id'), table_name='moderation_tasks')
    op.drop_index('idx_tasks_status_queue_created', table_name='moderation_tasks')
    op.drop_index('idx_tasks_status', table_name='moderation_tasks')
    op.drop_index('idx_tasks_queue_priority', table_name='moderation_tasks')
    op.drop_index('idx_tasks_product_id', table_name='moderation_tasks')
    op.drop_index('idx_tasks_assigned_moderator', table_name='moderation_tasks')
    op.drop_table('moderation_tasks')
    op.drop_index(op.f('ix_idempotency_keys_processed_at'), table_name='idempotency_keys')
    op.drop_index(op.f('ix_idempotency_keys_key'), table_name='idempotency_keys')
    op.drop_table('idempotency_keys')
    op.drop_index(op.f('ix_blocking_reasons_code'), table_name='blocking_reasons')
    op.drop_index('idx_blocking_reasons_is_active', table_name='blocking_reasons')
    op.drop_index('idx_blocking_reasons_hard_block', table_name='blocking_reasons')
    op.drop_table('blocking_reasons')
    # ### end Alembic commands ###
