"""Add moderators and refresh_tokens

Revision ID: c00e1659757f
Revises: 9f16f7ec0675
Create Date: 2026-06-03 17:03:59.287057

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c00e1659757f'
down_revision: Union[str, None] = '9f16f7ec0675'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
